services:
  postgres:
    image: postgres:15
    container_name: postgres-produtos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: produtosdb
    ports:
      - "5432:5432"